IMAGE_HEIGHT = 224
IMAGE_WIDTH = 224
CLASSES_NUM = 7
INPUT_SHAPE = (224, 224, 3)
MODIFIED_IMAGES_DIRECTORY = 'HAM_RESIZED'
ORIGINAL_IMAGES_DIRECTORY = 'HAM10015_merged'
MODIFIED_TEST_IMAGES_DIRECTORY = 'HAM_TEST_RESIZED'
